### ISSUE TITLE
skill issue

### ISSUE THREAD

**Issue by ama3nen** [GENTA7740/GENTA-HAX-DOCS#2]
nice constant case on functions also its shitty go delete this please

**Comment by ama3nen** [comment]
![image](https://user-images.githubusercontent.com/109434259/179395031-bc751a0a-4557-4f62-ace1-e7d377277590.png)
Also, what is this "API List" ???? Do you even have any idea of what an API is ??

**Comment by ama3nen** [comment]
why store positions as x and y just use vector autist

**Comment by GENTA7740** [comment]
^ just ignore this retard

**Comment by arky-arky** [comment]
> Just ignore this retard

i think youre the retard here
